/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashiermode;

import com.sun.glass.events.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Daniel
 */
public class PayCash extends javax.swing.JPanel {

    static JDialog openD;

    public PayCash() {
        //patient
        initComponents();

    }

    public JTextField getTotalTF() {
        return totalTF;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalL = new javax.swing.JLabel();
        pymentAL = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        paymentATF = new javax.swing.JTextField();
        OkB = new javax.swing.JButton();
        balanceL = new javax.swing.JLabel();

        totalL.setText("Amount To Pay");

        pymentAL.setText("Payment Amount");

        totalTF.setEditable(false);

        paymentATF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paymentATFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paymentATFKeyTyped(evt);
            }
        });

        OkB.setText("Ok");
        OkB.setEnabled(false);
        OkB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceL)
                    .addComponent(pymentAL)
                    .addComponent(totalL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OkB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(totalTF)
                        .addComponent(paymentATF, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalL)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pymentAL)
                    .addComponent(paymentATF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(balanceL)
                .addGap(18, 18, 18)
                .addComponent(OkB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OkBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkBActionPerformed
        // TODO add your handling code here:
        okButtonClick();

    }//GEN-LAST:event_OkBActionPerformed

    private void okButtonClick() {
        boolean status;
        int tests;
        tests = (Integer) Receipt.records.get(2);
        status = Receipt.db.updatePaymentState(tests, Receipt.patient.getId(), Receipt.cashierId, Receipt.doce, Receipt.labTest, Receipt.total);

        if (status) {
            Receipt rec = new Receipt(Receipt.cashierId);
            rec.getpayBillButton();
            JOptionPane.showMessageDialog(this, "Patient Bill Successfully Cleared ", "Successfull Payment", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Patient Payment Records Well Updated ");
            Receipt.generateReciept();
            Receipt.frame.setVisible(false);

            OpenDialogue open = new OpenDialogue();
            openD = new JDialog(new Receipt(Receipt.cashierId), "Reciept For " + Receipt.patient.getName(), true);
            openD.getContentPane().add(open);
            open.urlL().setText(Receipt.file.getAbsolutePath());
            openD.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            openD.setLocationRelativeTo(this);
            openD.pack();
            openD.setVisible(true);

        }

    }

    private void checkAmount() {
        if (!".".equals(paymentATF.getText().trim())) {
            if (Double.parseDouble(paymentATF.getText().trim()) >= Double.parseDouble(totalTF.getText().trim())) {
                OkB.setEnabled(true);

            } else {
                OkB.setEnabled(false);
            }
        }

    }

  

    private void paymentATFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentATFKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_ENTER) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_ENTER) || (c == '.') || (c == KeyEvent.VK_SPACE))) {
            System.out.println("here  " + c);
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Payment Amount cannot contain " + c, "Input Error", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }

        if (c == KeyEvent.VK_ENTER) {
            if (OkB.isEnabled()) {
                okButtonClick();
            } else {
                evt.consume();
                getToolkit().beep();
            }
        }

        if (c == KeyEvent.VK_SPACE) {
            evt.consume();
            getToolkit().beep();
        }

        if (c == '.') {
            if (paymentATF.getText().trim().contains(".")) {
                System.out.println("DOot Her");
                getToolkit().beep();
                JOptionPane.showMessageDialog(this, "Payment Amount Cannot Contain More Than One Decimal Point ", "Input Error", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
        if ((c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
            if (!paymentATF.getText().trim().isEmpty()) {
                checkAmount();
            }

        }


    }//GEN-LAST:event_paymentATFKeyTyped

    private void paymentATFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentATFKeyReleased
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_DECIMAL))) {
            evt.consume();
        } else {

            checkAmount();

            if ((c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE)) {
                checkAmount();

            }

        }
    }//GEN-LAST:event_paymentATFKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkB;
    private javax.swing.JLabel balanceL;
    private javax.swing.JTextField paymentATF;
    private javax.swing.JLabel pymentAL;
    private javax.swing.JLabel totalL;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
/*
for(int i =0 ; i< tests.size(); i++){
         status= Receipt.db.updatePaymentState(tests.get(i),Receipt.labTest,Receipt.total);
         
        
        }
        }
        else{
        status= Receipt.db.updatePaymentState((int) Receipt.records.get(2).get(0),0,Receipt.total);
         
        }
*/
