/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doctormode;

import java.awt.AWTEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.AWTEventListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

/**
 *
 * @author root
 */
public class DoctorMain extends javax.swing.JFrame {
    
    private Patient patient;
    private PatientRecord patientrecord;
    private Diagnosis diagnosis;
    private Prescription prescription;
    private LabTest labtest;
    private Test test;
    private Doctor doctor;
    private ArrayList<Test> alltests;
    private ArrayList<Test> testsresults;
    private DefaultListModel model;
    private DefaultListModel resultmodel;
    private String module;

    /**
     * Creates new form DoctorMain
     * @param module
     * @param doc_id
     * @param hos_name
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public DoctorMain(String module,int doc_id,String hos_name) throws SQLException, ClassNotFoundException {
        initComponents();
        touchup(doc_id,hos_name);
        this.module = module;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jFrame2 = new javax.swing.JFrame();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jFrame3 = new javax.swing.JFrame();
        jPanel14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jFrame4 = new javax.swing.JFrame();
        jPanel20 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jPanel24 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel22 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jFrame5 = new javax.swing.JFrame();
        jPanel25 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton13 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setTitle("Lab Tests");
        jFrame1.setSize(new java.awt.Dimension(301, 188));
        jFrame1.setType(java.awt.Window.Type.UTILITY);
        jFrame1.getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel9.setLayout(new java.awt.GridLayout(6, 1));

        jLabel14.setText("Lab Tests for:");
        jPanel9.add(jLabel14);
        jPanel9.add(jLabel15);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(jComboBox1);

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton6);

        jButton7.setText("Remove");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7);

        jButton8.setText("Done");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton8);

        jFrame1.getContentPane().add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel10.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jFrame1.getContentPane().add(jPanel10);

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame2.setTitle("Diagnosis");
        jFrame2.setSize(new java.awt.Dimension(301, 188));

        jLabel16.setText("Diagnosis for: ");
        jPanel11.add(jLabel16);
        jPanel11.add(jLabel17);

        jFrame2.getContentPane().add(jPanel11, java.awt.BorderLayout.NORTH);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel18.setText("Description:");
        jPanel12.add(jLabel18, java.awt.BorderLayout.NORTH);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBar(null);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel12.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jFrame2.getContentPane().add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jButton9.setText("Done");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton9, java.awt.BorderLayout.EAST);

        jFrame2.getContentPane().add(jPanel13, java.awt.BorderLayout.SOUTH);

        jFrame3.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame3.setTitle("Prescription");
        jFrame3.setSize(new java.awt.Dimension(301, 188));

        jLabel19.setText("Prescription for: ");
        jPanel14.add(jLabel19);
        jPanel14.add(jLabel20);

        jFrame3.getContentPane().add(jPanel14, java.awt.BorderLayout.NORTH);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel21.setText("Description:");
        jPanel15.add(jLabel21, java.awt.BorderLayout.NORTH);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setHorizontalScrollBar(null);

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel15.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jFrame3.getContentPane().add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel16.setLayout(new java.awt.BorderLayout());

        jButton10.setText("Done");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton10, java.awt.BorderLayout.EAST);

        jFrame3.getContentPane().add(jPanel16, java.awt.BorderLayout.SOUTH);

        jFrame4.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame4.setTitle("Lab Results");
        jFrame4.setSize(new java.awt.Dimension(242, 630));
        jFrame4.getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jPanel20.setLayout(new java.awt.GridLayout(1, 2));

        jPanel23.setLayout(new java.awt.BorderLayout());

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(jList2);

        jPanel23.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel23);

        jPanel24.setLayout(new java.awt.GridLayout(3, 0));

        jLabel25.setText("Lab Results for:");
        jPanel24.add(jLabel25);

        jLabel26.setText("Mr. mburu");
        jPanel24.add(jLabel26);

        jButton12.setText("Done");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel24.add(jButton12);

        jPanel20.add(jPanel24);

        jFrame4.getContentPane().add(jPanel20);

        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel24.setText("Description:");
        jPanel21.add(jLabel24, java.awt.BorderLayout.NORTH);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jPanel21.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jFrame4.getContentPane().add(jPanel21);

        jPanel22.setLayout(new java.awt.BorderLayout());

        jLabel23.setText("Results:");
        jPanel22.add(jLabel23, java.awt.BorderLayout.NORTH);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel22.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jFrame4.getContentPane().add(jPanel22);

        jPopupMenu1.setInvoker(jButton1);

        jMenuItem1.setText("logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("change password");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jFrame5.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame5.setTitle("Change Password");
        jFrame5.setSize(new java.awt.Dimension(400, 353));

        jLabel27.setText("Change Password");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel28.setText("New Password");

        jLabel29.setText("Confirm Password");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton13.setText("Save");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 300));
        setSize(new java.awt.Dimension(700, 300));
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setText("hospital name");
        jPanel3.add(jLabel1);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Dr. Steve");
        jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);

        jButton1.setText("Account");
        jButton1.setComponentPopupMenu(jPopupMenu1);
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton1FocusLost(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel17.setLayout(new java.awt.GridLayout(1, 2));

        jPanel18.setLayout(new java.awt.GridLayout(2, 1));

        jLabel3.setText("Patient ID:");
        jPanel18.add(jLabel3);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel18.add(jTextField1);

        jPanel17.add(jPanel18);

        jPanel19.setLayout(new java.awt.GridLayout(2, 1));

        jLabel22.setText("Patient Record ID:");
        jPanel19.add(jLabel22);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel19.add(jTextField2);

        jPanel17.add(jPanel19);

        jPanel4.add(jPanel17, java.awt.BorderLayout.CENTER);

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, java.awt.BorderLayout.EAST);
        jPanel4.add(jLabel4, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jLabel5, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout(4, 2));

        jLabel6.setText("Name:");
        jPanel7.add(jLabel6);
        jPanel7.add(jLabel7);

        jLabel8.setText("Age:");
        jPanel7.add(jLabel8);
        jPanel7.add(jLabel9);

        jLabel10.setText("Gender:");
        jPanel7.add(jLabel10);
        jPanel7.add(jLabel11);

        jLabel12.setText("Nat. ID:");
        jPanel7.add(jLabel12);
        jPanel7.add(jLabel13);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(4, 0));

        jButton3.setText("Recommend Lab Test");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3);

        jButton11.setText("View Lab Results");
        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11);

        jButton4.setText("Diagnose");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4);

        jButton5.setText("Prescribe");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5);

        jPanel6.add(jPanel8, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // search button clicked
        if(!jTextField1.getText().isEmpty() && !jTextField2.getText().isEmpty()){
            jLabel4.setText("searching...");
            int patientid = Integer.parseInt(jTextField1.getText());
            try {
                this.patient = new Patient();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                if(this.patient.searchPatient(patientid)){
                    //set the labels
                    jLabel7.setText(this.patient.getFirstname()+" "+this.patient.getLastname());
                    jLabel9.setText(this.patient.getAge()+"");
                    jLabel11.setText(this.patient.getGender());
                    jLabel13.setText(this.patient.getNationalID()+"");
                    jLabel4.setForeground(Color.green);
                    jLabel5.setForeground(Color.green);
                    jLabel4.setText("search completed");
                    jLabel5.setText("1 match found!");
                    jButton3.setEnabled(true);
                    jButton4.setEnabled(true);
                    jButton5.setEnabled(true);
                    jButton11.setEnabled(true);
                    checkPatientRecord(patientid);

                }else {
                    jLabel4.setForeground(Color.red);
                    jLabel5.setForeground(Color.red);
                    jLabel4.setText("search completed");
                    jLabel5.setText("no match found!");
                    jButton3.setEnabled(false);
                    jButton4.setEnabled(false);
                    jButton5.setEnabled(false);
                    jButton11.setEnabled(false);
                    jLabel7.setText("");
                    jLabel9.setText("");
                    jLabel11.setText("");
                    jLabel13.setText("");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            String opt = "";
            if(jTextField1.getText().isEmpty() && !jTextField2.getText().isEmpty())
                opt = "Patient ID Field";
            else if(jTextField2.getText().isEmpty() && !jTextField1.getText().isEmpty())
                opt = "PatientRecord ID Field";
            else if(jTextField1.getText().isEmpty() && jTextField2.getText().isEmpty())
                opt = "Both Patient ID Field and PatientRecord ID Field";
            JOptionPane.showMessageDialog(rootPane, opt+" cannot be empty. Enter digits[0-9]", opt+" Empty", JOptionPane.ERROR_MESSAGE);
            jTextField1.requestFocus();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Enter clicked on search patient id
        jButton2ActionPerformed(evt);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // Recommend Lab tests button clicked
            this.test = new Test();
            this.alltests = Test.getAlltests();
            setAllTests();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jLabel15.setText(this.patient.getFirstname()+" "+this.patient.getLastname());
        jFrame1.setLocationRelativeTo(this);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void setAllTests(){
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(Test.getTestTitles()));
        model = new javax.swing.DefaultListModel();
        jList1.setModel(model);
    }
    
    private void touchup(int doc_id,String hos_name) throws SQLException, ClassNotFoundException{
        this.doctor = new Doctor(doc_id);
        this.setTitle(this.doctor.getName()+" | "+hos_name);
        this.jLabel1.setText(hos_name);
        this.jLabel2.setText(this.doctor.getName());
    }
    
    private void checkPatientRecord(int patientid) throws ClassNotFoundException, SQLException{
        int patrec_id = Integer.parseInt(jTextField2.getText());
        this.patientrecord =  new PatientRecord();
        if(!patientrecord.checkRecordExists(patientid, patrec_id)){
            JOptionPane.showMessageDialog(rootPane, "This Patient Record ID doesn't correspond to this Patient ID. Please use the proper Record ID", "ID Mismatch", JOptionPane.ERROR_MESSAGE);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton11.setEnabled(false);
        }
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // Diagnose button clicked
            this.diagnosis = new Diagnosis(this.patient.getId(),this.patientrecord.getId(),this.doctor.getId());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(this.diagnosis.checkExistDesc()){
                jTextArea1.setText(this.diagnosis.getDescription());
            }
        } catch (SQLException ex) {
            Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel17.setText(this.patient.getFirstname()+" "+this.patient.getLastname());
        jFrame2.setLocationRelativeTo(this);
        jFrame2.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // Prescribe button clicked
            this.prescription = new Prescription(this.patient.getId(),this.patientrecord.getId(),this.doctor.getId());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(this.prescription.checkExistDesc()){
                jTextArea2.setText(this.prescription.getDescription());
                System.out.println("set on field");
            }
            System.out.println("not set on field");
        } catch (SQLException ex) {
            Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel20.setText(this.patient.getFirstname()+" "+this.patient.getLastname());
        jFrame3.setLocationRelativeTo(this);
        jFrame3.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // submitting diagnosis description
        String desc = jTextArea1.getText();
        if(!desc.isEmpty()){
            try {
                this.diagnosis.setDescription(desc);
                JOptionPane.showMessageDialog(rootPane, "Diagnosis was submitted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "The Diagnosis is not typed in", "Empty Diagnosis", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // submitting prescription description
        String desc = jTextArea2.getText();
        if(!desc.isEmpty()){
            try {
                this.prescription.setDescription(desc);
                JOptionPane.showMessageDialog(rootPane, "Prescription was submitted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "The prescription is not typed in", "Empty Prescription", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Add button clicked in lab test window
        String temp = jComboBox1.getSelectedItem().toString();
        if(!model.contains(temp))
            model.addElement(temp);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // delete button clicked in test window
        for(int i = 0;i<model.getSize();i++){
            if(model.elementAt(i).toString().contains(jComboBox1.getSelectedItem().toString())){
                model.removeElementAt(i);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(!model.isEmpty()){
            try {
                // done button clicked in lab test window
                this.labtest = new LabTest(this.patient.getId(),this.patientrecord.getId());
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int i = 0;i<model.getSize();i++){
                for (Test alltest : alltests) {
                    if(model.elementAt(i).toString().contains(alltest.getTitle())){
                        this.labtest.addTest(alltest);
                    }
                }
            }
            try {
                this.labtest.writeLabtest2DB();
                JOptionPane.showMessageDialog(rootPane, "Test submitted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Cannot submit an empty test!", "Empty Test", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // View lab results button clicked
        this.resultmodel = new DefaultListModel();
        try {
            this.labtest = new LabTest();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.labtest.getTestsfromDB(this.patientrecord.getId());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(DoctorMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.testsresults = this.labtest.getTests();
        this.testsresults.stream().forEach((testt) -> {
            this.resultmodel.addElement(testt.getTitle());
        });
        jList2.setModel(this.resultmodel);
        
        jLabel26.setText(this.patient.getFirstname()+" "+this.patient.getLastname());
        jFrame4.setLocationRelativeTo(this);
        jFrame4.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        // Lab results selection change in list model
        if(!this.testsresults.isEmpty()){
            this.testsresults.stream().forEach((testt) -> {
                if(!jList2.isSelectionEmpty()){
                    if(jList2.getSelectedValue().toString().contains(testt.getTitle())){
                        jTextArea4.setText(testt.getDescription());
                        jTextArea3.setText(testt.getResults());
                    }
                }
            });
        }
    }//GEN-LAST:event_jList2ValueChanged

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // done button clicked in view lab results
        if(!jList2.isSelectionEmpty())
            jList2.clearSelection();
        jFrame4.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // Enter clicked on search patient record id
        jButton2ActionPerformed(evt);
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // key typed in patient id field
        String ky = evt.getKeyChar()+"";
        String validat = "0123456789";
        if(!ky.equals("\n") && !ky.equals("\b") && !validat.contains(ky)){
            JOptionPane.showMessageDialog(rootPane, "Patient id cannot contain character "+ky+". Enter digits[0-9]", "Invalid character "+ky, JOptionPane.ERROR_MESSAGE);
            evt.consume();
            jTextField1.setText("");
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // key typed in patient record id field
        String ky = evt.getKeyChar()+"";
        String validat = "0123456789";
        if(!ky.equals("\n") && !ky.equals("\b") && !validat.contains(ky)){
            JOptionPane.showMessageDialog(rootPane, "PatientRecord id cannot contain character "+ky+". Enter digits[0-9]", "Invalid character "+ky, JOptionPane.ERROR_MESSAGE);
            evt.consume();
            jTextField2.setText("");
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // logout selected
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // change password selected
        jFrame5.setLocationRelativeTo(this);
        jFrame5.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // account button clicked
        if(jPopupMenu1.isVisible())
            jPopupMenu1.getComponent().setVisible(false);
        else
            jPopupMenu1.show((Component)evt.getSource(), 0, 25);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusLost
        // focus lost from account button
        jPopupMenu1.getComponent().setVisible(false);
    }//GEN-LAST:event_jButton1FocusLost

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // enter clicked in confirm password field
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // Login button clicked in login window
        if(!(jPasswordField2.getPassword().length == 0) && !(jPasswordField1.getPassword().length == 0)){
            char[] newpassword = jPasswordField2.getPassword();
            char[] confpassword = jPasswordField1.getPassword();
            if(String.copyValueOf(newpassword).equals(String.copyValueOf(confpassword))){
                try {
                    Login login = new Login(this.module,this.doctor.getId());
                    if(login.changePasswd(newpassword)){
                        JOptionPane.showMessageDialog(rootPane, "The Password was Changed successfully!", "Change Successful!", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "The Password change failed", "Change Failure", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "The Passwords do not match!", "Password Mismatch", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            String opt = "";
            if((jPasswordField2.getPassword().length == 0) && !(jPasswordField1.getPassword().length == 0))
            opt = "New Password Field";
            else if(jPasswordField1.getPassword().length == 0 && !(jPasswordField2.getPassword().length == 0))
            opt = "Confirm Password Field";
            else if(jPasswordField2.getPassword().length == 0 && jPasswordField1.getPassword().length == 0)
            opt = "Both New Password Field and Confirm Password Field";
            JOptionPane.showMessageDialog(rootPane, opt+" cannot be empty.", opt+" Empty", JOptionPane.ERROR_MESSAGE);
            jPasswordField2.requestFocus();
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // enter clicked in new password field 
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
