/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package receptionistmode;

import com.sun.glass.events.KeyEvent;
import doctormode.Doctor;
import doctormode.Patient;
import doctormode.PatientRecord;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author root
 */
public class ReceptionistMain extends javax.swing.JFrame {

    private Receptionist receptionist;
    private Patient patient;
    private PatientRecord patientrecord;
    private Appointment appointment;

    /**
     * Creates new form ReceptionistMain
     *
     * @param recept_id
     * @param hos_name
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public ReceptionistMain(int recept_id, String hos_name) throws SQLException, ClassNotFoundException {
        initComponents();
        touchup(recept_id, hos_name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bloodgroup = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        health_history = new javax.swing.JTextArea();
        age_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        national_id = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cellphone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        homephone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        postalcode = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        po_box = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        street = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        patie_id1 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        appoint_tbl = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        clearbtn1 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        assignbtn = new javax.swing.JButton();
        doc_id_item = new javax.swing.JComboBox();
        patient_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        searchbtn = new javax.swing.JButton();
        search_text = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        search_result_tbl = new javax.swing.JTable();
        checkinbtn = new javax.swing.JButton();
        checkoutbtn = new javax.swing.JButton();
        regbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        patient_tbl1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patie_id = new javax.swing.JLabel();
        patie1_id = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame1.setMaximumSize(new java.awt.Dimension(700, 600));
        jFrame1.setPreferredSize(new java.awt.Dimension(700, 550));
        jFrame1.setResizable(false);
        jFrame1.setSize(new java.awt.Dimension(700, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Infomation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel3.setText("Firstname");

        txtfirstname.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel4.setText("Lastname");

        txtlastname.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel5.setText("Age");

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel6.setText("Blood group");

        bloodgroup.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        bloodgroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A +ve", "A -ve", "O +ve", "O -ve", "AB +ve", "AB -ve", "B -ve", "B +ve" }));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel7.setText("Gender");

        gender.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel8.setText("Health History");

        health_history.setColumns(20);
        health_history.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        health_history.setRows(5);
        jScrollPane1.setViewportView(health_history);

        age_txt.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        age_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                age_txtKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel13.setText("nationalID");

        national_id.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        national_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                national_idKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfirstname)
                    .addComponent(txtlastname)
                    .addComponent(bloodgroup, 0, 151, Short.MAX_VALUE)
                    .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(age_txt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(national_id))))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addComponent(national_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(age_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(bloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Contact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel9.setText("Cell Phone");

        cellphone.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        cellphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cellphoneKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel10.setText("Home Phone");

        homephone.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        homephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homephoneKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel11.setText("Postal code");

        postalcode.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        postalcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                postalcodeKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel12.setText("P.o. Box No.");

        po_box.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel14.setText("City");

        city.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel15.setText("Street");

        street.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N

        savebtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        clearbtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        exitbtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cellphone)
                    .addComponent(homephone)
                    .addComponent(postalcode)
                    .addComponent(po_box, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(patie_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cellphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savebtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(homephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbtn))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(exitbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patie_id1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(po_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel16)))
                .addGap(45, 45, 45))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 255));
        jLabel17.setText("NEW PATIENT REGISTRATION");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame2.setResizable(false);
        jFrame2.setSize(new java.awt.Dimension(648, 450));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Appointment Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(102, 102, 255))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        appoint_tbl.setBackground(new java.awt.Color(204, 204, 204));
        appoint_tbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        appoint_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appoint-Id", "Doctor", "Date of appointment", "Patient_Id"
            }
        ));
        appoint_tbl.setCellSelectionEnabled(true);
        jScrollPane4.setViewportView(appoint_tbl);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 255));
        jLabel18.setText("DOCTOR'S APPOINTMENT PANEL");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assign New Appointment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(102, 102, 255))); // NOI18N
        jPanel5.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel19.setText("Patient-Id");

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel20.setText("Doctor's Id");

        clearbtn1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        clearbtn1.setText("Clear");
        clearbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtn1ActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        assignbtn.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        assignbtn.setText("Assign New Doctor");
        assignbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignbtnActionPerformed(evt);
            }
        });

        doc_id_item.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));

        patient_id.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doc_id_item, 0, 146, Short.MAX_VALUE)
                    .addComponent(patient_id))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 163, Short.MAX_VALUE)
                .addComponent(assignbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patient_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doc_id_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearbtn1)
                    .addComponent(Exit)
                    .addComponent(assignbtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(619, 476));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Patient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 11)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        searchbtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        search_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_textActionPerformed(evt);
            }
        });
        search_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_textKeyTyped(evt);
            }
        });

        search_result_tbl.setBackground(new java.awt.Color(204, 204, 204));
        search_result_tbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        search_result_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient- Id", "National ID", "Firstname", "Lastname", "Age", "Gender"
            }
        ));
        search_result_tbl.setSelectionBackground(new java.awt.Color(153, 153, 255));
        search_result_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_result_tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(search_result_tbl);

        checkinbtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        checkinbtn.setText("Check in");
        checkinbtn.setEnabled(false);
        checkinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinbtnActionPerformed(evt);
            }
        });

        checkoutbtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        checkoutbtn.setText("Check out");
        checkoutbtn.setEnabled(false);
        checkoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutbtnActionPerformed(evt);
            }
        });

        regbtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        regbtn.setText("Register");
        regbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtnActionPerformed(evt);
            }
        });

        patient_tbl1.setBackground(new java.awt.Color(204, 204, 204));
        patient_tbl1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        patient_tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient- Id", "National ID", "Firstname", "Lastname", "Age", "Gender"
            }
        ));
        patient_tbl1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        patient_tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient_tbl1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(patient_tbl1);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("SEARCH RESULT");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("PATIENT RECORDS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(search_text)
                .addGap(18, 18, 18)
                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patie_id, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patie1_id, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbtn)
                    .addComponent(search_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patie1_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patie_id)
                    .addComponent(id_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkinbtn)
                    .addComponent(checkoutbtn)
                    .addComponent(regbtn))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void touchup(int recept_id, String hos_name) throws SQLException, ClassNotFoundException {
        this.receptionist = new Receptionist(recept_id);
        this.setTitle(this.receptionist.getName() + " | " + hos_name);
        this.setLocationRelativeTo(null);
        try {
            this.patient = new Patient();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateAllPatienttable(this.patient.getAllPatients());
    }

    private void updateSearchResulttable(ResultSet rst) throws SQLException {
        //updates the search results table
        search_result_tbl.setModel(DbUtils.resultSetToTableModel(rst));
    }

    private void updateAllPatienttable(ResultSet rst) throws SQLException {
        //updates the search results table
        patient_tbl1.setModel(DbUtils.resultSetToTableModel(rst));
    }

    private void search_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_textKeyTyped
        // key typed in search patient id field
        String ky = evt.getKeyChar() + "";
        String validat = "0123456789";
        if (!ky.equals("\n") && !ky.equals("\b") && !validat.contains(ky)) {
            JOptionPane.showMessageDialog(rootPane, "Patient id cannot contain character " + ky + ". Enter digits[0-9]", "Invalid character " + ky, JOptionPane.ERROR_MESSAGE);
            evt.consume();
            search_text.setText("");
            search_text.requestFocus();
        }
    }//GEN-LAST:event_search_textKeyTyped

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // search button clicked:
        String id_val = search_text.getText();
        if (!id_val.isEmpty()) {
            try {
                if (this.patient.searchPatient(Integer.parseInt(id_val))) {
                    updateSearchResulttable(this.patient.getTempresultSet());
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Patient id provided doesn't match any existing patient", "Patient Not Found", JOptionPane.ERROR_MESSAGE);
                    search_text.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Patient id field is empty", "Empty Field", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void search_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_textActionPerformed
        // enter clicked in search patient id text field:
        searchbtnActionPerformed(evt);
    }//GEN-LAST:event_search_textActionPerformed

    private void patient_tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient_tbl1MouseClicked
        // mouse click on all patients table:

        int selecRow = patient_tbl1.getSelectedRow();
        if (selecRow != -1) {
            search_result_tbl.clearSelection();
            checkinbtn.setEnabled(true);
            checkoutbtn.setEnabled(true);
        } else {
            search_result_tbl.clearSelection();
            patient_tbl1.clearSelection();
            checkinbtn.setEnabled(false);
            checkoutbtn.setEnabled(false);
        }
    }//GEN-LAST:event_patient_tbl1MouseClicked

    private void search_result_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_result_tblMouseClicked
        // mouse click on all search result table:

        int selecRow = search_result_tbl.getSelectedRow();
        if (selecRow != -1) {
            patient_tbl1.clearSelection();
            checkinbtn.setEnabled(true);
            checkoutbtn.setEnabled(true);
        } else {
            patient_tbl1.clearSelection();
            search_result_tbl.clearSelection();
            checkinbtn.setEnabled(false);
            checkoutbtn.setEnabled(false);
        }
    }//GEN-LAST:event_search_result_tblMouseClicked

    private int checkPatID() {
        int patient_id = 0;
        if (patient_tbl1.getSelectedRow() != -1) {
            patient_id = (int) patient_tbl1.getValueAt(patient_tbl1.getSelectedRow(), 0);
        } else if (search_result_tbl.getSelectedRow() != -1) {
            patient_id = (int) search_result_tbl.getValueAt(search_result_tbl.getSelectedRow(), 0);
        } else {
            JOptionPane.showMessageDialog(rootPane, "No patient is selected from tables", "No selection", JOptionPane.ERROR_MESSAGE);
        }
        return patient_id;
    }

    private void checkinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinbtnActionPerformed
        // checkin button clicked
        int patient_idd = checkPatID();
        if (patient_idd != 0) {
            try {
                this.patient = new Patient(patient_idd);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                this.patientrecord = new PatientRecord(this.patient.getId());
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                this.patientrecord.createRecord();
                JOptionPane.showMessageDialog(null, "PatientRecord Successfully created with PatientRecord ID: " + this.patientrecord.getId(), "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                newAppointment();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_checkinbtnActionPerformed

    private void checkoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutbtnActionPerformed
        // checkout button clicked:
        int patient_idd = checkPatID();
        if (patient_idd != 0) {
            //use this to check whether patient has any open records
            JOptionPane.showMessageDialog(null, "Patient checked out successfully", "Success checkout", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_checkoutbtnActionPerformed

    private void regbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtnActionPerformed
        // register button clicked
        jFrame1.setLocationRelativeTo(this);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_regbtnActionPerformed

    private void age_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_txtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (age_txt.getText().trim().length() > 2) {
            JOptionPane.showMessageDialog(null, "Age cannot be more than 3 digits", "Invalid input", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            evt.consume();
        }

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(null, "Age cannot contain " + c, "Invalid input", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_age_txtKeyTyped

    private void national_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_national_idKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (national_id.getText().trim().length() > 8) {
            JOptionPane.showMessageDialog(null, "National ID cannot be more than 8 digits", "Invalid input", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            evt.consume();
        }

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(null, "National Id cannot contain " + c, "Invalid input", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_national_idKeyTyped

    private void cellphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cellphoneKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (cellphone.getText().trim().length() > 9) {
            JOptionPane.showMessageDialog(null, "Phone Number cannot be more than 10 digits ", "Invalid input", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            evt.consume();
        }

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(null, "Phone Number cannot contain " + c, "Invalid input", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_cellphoneKeyTyped

    private void homephoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homephoneKeyTyped
        char c = evt.getKeyChar();
        try {
            if (homephone.getText().trim().length() > 9) {
            getToolkit().beep();
            evt.consume();
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Phone Number cannot be more than 10 digits ", "Invalid input", JOptionPane.ERROR_MESSAGE);
        }
        

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(null, "Cellphone Number cannot contain " + c, "Invalid input", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_homephoneKeyTyped

    private void postalcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postalcodeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (postalcode.getText().trim().length() > 4) {
            JOptionPane.showMessageDialog(null, "postal code cannot be more than 5 digits", "Invalid input", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            evt.consume();
        }

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(null, "postal code cannot contain " + c, "Invalid input", JOptionPane.ERROR_MESSAGE);
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_postalcodeKeyTyped

    private void validateFields(java.awt.event.ActionEvent evt) {
        //check if all important fields are filled if not consume event
    }

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        validateFields(evt);
        String firstname = this.txtfirstname.getText();
        String lastname = this.txtlastname.getText();
        int cellphoneS = Integer.parseInt(this.cellphone.getText());
        int homephoneS = Integer.parseInt(this.homephone.getText());
        int age = Integer.parseInt(this.age_txt.getText());
        int nationalID = Integer.parseInt(this.national_id.getText());
        String po_boxS = this.po_box.getText();
        int postalcodeS = Integer.parseInt(this.postalcode.getText());
        String cityS = this.city.getText();
        String streetS = this.street.getText();
        String health_historyS = this.health_history.getText();
        String blood_group = (String) this.bloodgroup.getSelectedItem();
        String genderS = (String) this.gender.getSelectedItem();

        try {
            this.patient = new Patient(nationalID, firstname, lastname, age, genderS, blood_group, health_historyS, cellphoneS, homephoneS, postalcodeS, po_boxS, cityS, streetS);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            this.patient.addToDb13();
            JOptionPane.showMessageDialog(null, "Patient Successfully created with Patient ID: " + this.patient.getId(), "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.patientrecord = new PatientRecord(this.patient.getId());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.patientrecord.createRecord();
            JOptionPane.showMessageDialog(null, "PatientRecord Successfully created with PatientRecord ID: " + this.patientrecord.getId(), "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            // then create new appointment
            newAppointment();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        txtfirstname.setText("");
        txtlastname.setText("");
        cellphone.setText("");
        homephone.setText("");
        health_history.setText("");
        city.setText("");
        national_id.setText("");
        postalcode.setText("");
        po_box.setText("");
        street.setText("");
        age_txt.setText("");
        gender.setSelectedItem(this);
        bloodgroup.setSelectedItem(this);
    }//GEN-LAST:event_clearbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        jFrame1.dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void newAppointment() throws ClassNotFoundException, SQLException {
        patient_id.setText(this.patient.getId() + "");
        updateAppointmentsTable(new Appointment().getAllAppoints());
        updateDoctorsCombo();
        jFrame2.setLocationRelativeTo(this);
        jFrame2.setVisible(rootPaneCheckingEnabled);
    }

    private void updateAppointmentsTable(ResultSet rst) {
        appoint_tbl.setModel(DbUtils.resultSetToTableModel(rst));
    }

    private void updateDoctorsCombo() throws ClassNotFoundException, SQLException{
        doc_id_item.setModel(new javax.swing.DefaultComboBoxModel(Doctor.getDocIds()));
    }
    
    private void clearbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtn1ActionPerformed
        patient_id.setText("");
        doc_id_item.setSelectedItem("");
        //date_of_Appointment.setDate(null);

    }//GEN-LAST:event_clearbtn1ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        jFrame2.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void assignbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignbtnActionPerformed
        //int doc_id = (int) doc_id_item.getSelectedItem();
        int doc_id = Integer.parseInt((String) doc_id_item.getSelectedItem());
        try {
            this.appointment = new Appointment(doc_id,this.patient.getId(),this.receptionist.getId());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            //then call create appointment
            this.appointment.createAppoint();
            JOptionPane.showMessageDialog(null, "Appointment Successfully created with Appointment ID: " + this.appointment.getId(), "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ReceptionistMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_assignbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JTextField age_txt;
    private javax.swing.JTable appoint_tbl;
    private javax.swing.JButton assignbtn;
    private javax.swing.JComboBox bloodgroup;
    private javax.swing.JTextField cellphone;
    private javax.swing.JButton checkinbtn;
    private javax.swing.JButton checkoutbtn;
    private javax.swing.JTextField city;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton clearbtn1;
    private javax.swing.JComboBox doc_id_item;
    private javax.swing.JButton exitbtn;
    private javax.swing.JComboBox gender;
    private javax.swing.JTextArea health_history;
    private javax.swing.JTextField homephone;
    public javax.swing.JLabel id_label;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField national_id;
    public javax.swing.JLabel patie1_id;
    private javax.swing.JLabel patie_id;
    public javax.swing.JLabel patie_id1;
    private javax.swing.JTextField patient_id;
    private javax.swing.JTable patient_tbl1;
    private javax.swing.JTextField po_box;
    private javax.swing.JTextField postalcode;
    private javax.swing.JButton regbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JTable search_result_tbl;
    private javax.swing.JTextField search_text;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField street;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    // End of variables declaration//GEN-END:variables
}
